  version: '3'
  services:
    elasticsearch:
      container_name: elasticsearch
      image: elasticsearch:8.7.1
      environment: ['CLI_JAVA_OPTS=-Xms2g -Xmx2g','bootstrap.memory_lock=true','discovery.type=single-node','xpack.security.enabled=false', 'xpack.security.enrollment.enabled=false']
      ports:
        - 9200:9200
      networks:
        - elastic
      ulimits:
        memlock:
          soft: -1
          hard: -1
        nofile:
          soft: 65536
          hard: 65536
      deploy:
        resources:
          limits:
            cpus: '2.0'
          reservations:
            cpus: '1.0'

    logstash:
      image: logstash:8.7.1
      container_name: log
      environment:
        discovery.seed_hosts: logstash
        LS_JAVA_OPTS: "-Xms512m -Xmx512m"
      volumes:
        - ./logstash.config:/usr/share/logstash/pipeline/logstash-nginx.config
      ports:
        - "5000:5000/tcp"
        - "5000:5000/udp"
        - "5044:5044"
        - "9600:9600"
      depends_on:
        - elasticsearch
      networks:
        - elastic
      command: logstash -f /usr/share/logstash/pipeline/logstash.config

    kibana:
      image: kibana:8.7.1
      container_name: kibana
      environment:
        XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: d1a66dfd-c4d3-4a0a-8290-2abcb83ab3aa
      ports:
        - 5601:5601
      networks:
        - elastic
      depends_on:
        - elasticsearch
      deploy:
        resources:
          limits:
            cpus: '2.0'
          reservations:
            cpus: '1.0'

  networks:
    elastic:
      driver: bridge
